### PR TITLE
Devanshe sharma

### PR DESCRIPTION
**Pull request by Devanshe15**

### CODE REVIEW

**Review by MridulTi — COMMENTED** [review]
make sure that the folder name is your own name instead of "JS Project"

**Review by MridulTi — APPROVED** [review]

**Comment by MridulTi** [comment]
@Devanshe15  create a new pull request and make sure that your folder is in one of the dedicated folders mentioned in the repository. If a new folder category is required then let me know!

**Comment by Devanshe15** [comment]
@MridulTi a new folder category is required for javascript applications because there is no folder as such is mentioned in which I can commit. That is why I first made the 'JS folder' and committed the changes to that.

**Comment by MridulTi** [comment]
@Devanshe15  does your project come under CRUD (Create, Read, Update, Delete)? If so then add your project there otherwise let me know I will create a new folder for 'JS Project'

**Comment by Devanshe15** [comment]
Okay. I will add both projects to the CRUD folder. should I keep both the project's name on my name?

**Pull request merged**
